### PR TITLE
Change FileName to FilePath, add Confluence prefix

### PR DESCRIPTION
**Pull request by FreZZZeR**
Fixes for small mistakes in Documentation
### Description

Fixes for small mistakes in Documentation for function Set-Attachment

### Motivation and Context

When I tryed use cmdlet Set-ConfluenceAttachment by Docs I had some error.
So I fixed it.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist

- [ ] My code follows the code style of this project.
- [ ] I have added Pester Tests that describe what my changes should do.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by lipkau** [comment]
Hello.

Thank you for the PR!
Can you please make one additional change?
Please remove `, Workflow` from `Help.Tests.ps1` on line `33`. The CI is now using powershell 7 and it no longer supports that value.
By doing this, the check should become green.

**Comment by FreZZZeR** [comment]
Hello!
@lipkau, it was line 53.
I removed workflow.

**Comment by lipkau** [comment]
@FreZZZeR : did you close this PR on purpose?

**Comment by FreZZZeR** [comment]
@lipkau, I was not sure how Azure Devops PipeLine works.
After I had read documentation and I created new PR with bug fix included fixes for build module testing.

**Comment by lipkau** [comment]
Sorry. I missed the other PR

**Pull request closed without merging**
