### PR TITLE
Allow for positional parameter in ConvertTo-StorageFormat

### PR DESCRIPTION
**Pull request by lipkau**
this closes issue #62 
this requires #65

### CODE REVIEW

**Comment by lipkau** [comment]
Because with the current code I get
image

**Comment by lipkau** [comment]
Now that #65 is merged, can you re-build the CI?

**Comment by brianbunke** [comment]
Looks good!

**Comment by brianbunke** [comment]
For future reference, `-Content` is listed below `-ApiUri` and `-Credential`, so positionally supplying the content wasn't going so well.

**Pull request merged**
